---

apiVersion: v1
kind: Namespace
metadata:
  name: acm-sample-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  namespace: acm-sample-app
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: helloweb
  namespace: acm-sample-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello
    tier: web
  sessionAffinity: None
  type: ClusterIP
---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: hello
  name: helloweb
  namespace: acm-sample-app
spec:
  host: helloweb.apps.cluster-kvl6m.kvl6m.sandbox2474.opentlc.com
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: helloweb
    weight: 100
